const SET_USER = 'SET_USER'
const GET_PROPERTS = 'GET_PROJECTS'
const ADD_PROJECT = 'ADD_PROJECT'
const SET_PROJECTS = 'SET_PROJECTS';

export {
    SET_USER,
    GET_PROPERTS,
    ADD_PROJECT,
    SET_PROJECTS
}